-- MySQL Script generated by MySQL Workbench
-- Sun 29 Jan 2017 08:52:03 PM EST
-- Model: Labo_Timer    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema labo_timer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema labo_timer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labo_timer` DEFAULT CHARACTER SET latin1 ;
USE `labo_timer` ;

-- -----------------------------------------------------
-- Table `labo_timer`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_timer`.`users` ;

CREATE TABLE IF NOT EXISTS `labo_timer`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(250) NOT NULL,
  `first_name` VARCHAR(250) NULL,
  `last_name` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labo_timer`.`administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_timer`.`administrator` ;

CREATE TABLE IF NOT EXISTS `labo_timer`.`administrator` (
  `password` VARCHAR(250) NOT NULL,
  `users_id` INT NOT NULL,
  INDEX `fk_administrator_users_idx` (`users_id` ASC),
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC),
  CONSTRAINT `fk_administrator_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `labo_timer`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `labo_timer`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `labo_timer`;
INSERT INTO `labo_timer`.`users` (`id`, `user_name`, `first_name`, `last_name`) VALUES (1, 'admin', 'Administrateur', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `labo_timer`.`administrator`
-- -----------------------------------------------------
START TRANSACTION;
USE `labo_timer`;
INSERT INTO `labo_timer`.`administrator` (`password`, `users_id`) VALUES ('admin', 1);

COMMIT;

