-- MySQL Script generated by MySQL Workbench
-- Wed 18 Oct 2017 01:33:50 PM EDT
-- Model: Labo_Timer    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema labo_timer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema labo_timer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labo_timer` DEFAULT CHARACTER SET latin1 ;
USE `labo_timer` ;

-- -----------------------------------------------------
-- Table `labo_timer`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_timer`.`users` ;

CREATE TABLE IF NOT EXISTS `labo_timer`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(250) NOT NULL,
  `first_name` VARCHAR(250) NULL,
  `last_name` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `labo_timer`.`administrators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_timer`.`administrators` ;

CREATE TABLE IF NOT EXISTS `labo_timer`.`administrators` (
  `password` VARCHAR(250) NOT NULL,
  `users_id` INT NOT NULL,
  INDEX `fk_administrator_users_idx` (`users_id` ASC),
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC),
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_administrator_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `labo_timer`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labo_timer`.`laboratories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_timer`.`laboratories` ;

CREATE TABLE IF NOT EXISTS `labo_timer`.`laboratories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `password` VARCHAR(45) NULL,
  `date_start` VARCHAR(45) NOT NULL,
  `date_end` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labo_timer`.`guests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_timer`.`guests` ;

CREATE TABLE IF NOT EXISTS `labo_timer`.`guests` (
  `users_id` INT NOT NULL,
  `laboratories_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `laboratories_id`),
  INDEX `fk_users_has_laboratories_laboratories1_idx` (`laboratories_id` ASC),
  INDEX `fk_users_has_laboratories_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_laboratories_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `labo_timer`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_laboratories_laboratories1`
    FOREIGN KEY (`laboratories_id`)
    REFERENCES `labo_timer`.`laboratories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labo_timer`.`interventions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_timer`.`interventions` ;

CREATE TABLE IF NOT EXISTS `labo_timer`.`interventions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time_start` VARCHAR(45) NOT NULL,
  `time_end` VARCHAR(45) NOT NULL,
  `guests_users_id` INT NOT NULL,
  `guests_laboratories_id` INT NOT NULL,
  PRIMARY KEY (`id`, `guests_users_id`, `guests_laboratories_id`),
  INDEX `fk_intervention_guests1_idx` (`guests_users_id` ASC, `guests_laboratories_id` ASC),
  CONSTRAINT `fk_intervention_guests1`
    FOREIGN KEY (`guests_users_id` , `guests_laboratories_id`)
    REFERENCES `labo_timer`.`guests` (`users_id` , `laboratories_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labo_timer`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_timer`.`groups` ;

CREATE TABLE IF NOT EXISTS `labo_timer`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labo_timer`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labo_timer`.`members` ;

CREATE TABLE IF NOT EXISTS `labo_timer`.`members` (
  `users_id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `groups_id`),
  INDEX `fk_users_has_groups_groups1_idx` (`groups_id` ASC),
  CONSTRAINT `fk_users_has_groups_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `labo_timer`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_groups_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `labo_timer`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `labo_timer`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `labo_timer`;
INSERT INTO `labo_timer`.`users` (`id`, `user_name`, `first_name`, `last_name`) VALUES (1, 'admin', 'Administrateur', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `labo_timer`.`administrators`
-- -----------------------------------------------------
START TRANSACTION;
USE `labo_timer`;
INSERT INTO `labo_timer`.`administrators` (`password`, `users_id`) VALUES ('0x8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918', 1);

COMMIT;

